### ISSUE TITLE
request: to set default payment method (already selected)

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#166]
HI, please add an option in backend for us to set the already selected payment option

with other PSP we had this option and it works good, by taking away 1 click (and here by increasing conversion)

in our store we see 90% is one and the same payment option

so we would like to be able to set the pre-selected option in the backend to support our customers

thanks

**Comment by rikterbeek** [comment]
Hi Sean,

By extracting all payment methods as a different payment method in Magento this is now the responsibility of the checkout system. We can not include this into the module because all checkout modules work differently. We want to provide a module that works for any checkout module. I think there are plugins available that makes this possible.

Regards,
Rik ter Beek
Adyen
