### ISSUE TITLE
Save credit card information in your localstorage

### ISSUE THREAD

**Issue by paales** [Adyen/magento#233]
We use a one step checkout design for our checkout process. When filling in address information the payment information reloads and this causes the credit card information to be lost. It may be possible to save this information in your local storage so the customer has the information saved.

![schermafbeelding 2015-03-11 om 16 10 31](https://cloud.githubusercontent.com/assets/1244416/6599272/2cf3e434-c809-11e4-8f2b-04a4f0cafb80.png)

**Comment by rikterbeek** [comment]
Hi Paul,

I don't think we can solve this issue in our module. I see that you are using an external checkout module. What you can do is for the reloading of the payment methods save the creditcard details in javascript. After the Ajax call and refreshing the payment information you update the values with the details you have stored earlier. I think this is the only possibility because other solution are creating security flaws.

Regards,
Rik ter Beek
Adyen

**Comment by paales** [comment]
@rikterbeek Good point. We'll roll our own solution.
