### ISSUE TITLE
Boleto pdf not being generated

### ISSUE THREAD

**Issue by LemosT** [Adyen/magento#282]
Greetings. I've encountered a problem with the pdf generation when paying via Boleto. The function that should output the pdf ($this->getInfo()->getOrder()->getAdyenBoletoPdf()) actually outputs only the number for the Boleto. Furthermore, the attribute being called in that function (adyen_boleto_pdf) is actually of type text, not the recommended type for storing a pdf file (http://stackoverflow.com/questions/3092580/what-is-the-best-way-to-store-binary-data-images-pdfs-mp3s-videos-ect-in).

**Comment by rikterbeek** [comment]
Hi LemosT,

Thanks for letting us know! The column is text because we save a url to the pdf not the pdf itself. I see that it is not working anymore because the url is in the result but not as the first item. Now it is saving the boletobancario.barCodeReference. I changed the code so it will look for the entry boletobancario.url and use this becasue here is always the url returned. See code change below what you need to change.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi LemosT,

This should work for you as well. I am closing the issue let me know if you still have questions.

Regards,
Rik
Adyen
