### ISSUE TITLE
Checkout notice for CC and incorrect calculation?

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#372]
Hi, we are seeing the following. See below. 

** GT is 43,72. But the Adyen notice is payment of 40.00??

** And we didn't select CC payment. We selected Paypal in checkout. (see the small notice txt)

![image](https://cloud.githubusercontent.com/assets/652395/8844576/e4a693ee-3116-11e5-9fa1-9b117f30ea1e.png)

**Comment by rikterbeek** [comment]
Hi Sean,

This is not an Adyen notice but an Magento notice. I have checked it and it will occure for all payment methods(as well for native magento payment methods) when you are checking out with a different currency that the base currency. I think the best solution is to set the checkout currency the same as the base currency is that possible ? Or remove this text in the layout file because we will charge the transaction with the dollar amount in this case 43.72.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
OK
