### ISSUE TITLE
Adding 1 cent to payment magically?

### ISSUE THREAD

**Issue by frenck** [Adyen/magento#397]
This commit came by: add 1 cent payment fee for payment method Ideal,Sofort and SEPA if grand total and total amount is zero because otherwise payment will fail (30c2e8ae7bc1725fcb2b411220949c830ec6c8cb)

I know this fixes things... but really? This should not be the place, hell, this should not even be the right solution!

Magically adding 1 cent, so a customer HAS to pay? Even though the customer SHOULD NOT pay? That does not sound right.

I guess you guys should fix this on the Adyen side, if a shop enters with a payment of zero, nada, nothing, automatically approve the "payment", without bothering the customer. Or maybe enable a special "Free Payment" payment type or something.

Also, how does a shop owner / financial controller be able to justify the magically appeared 1 extra cent in their books (the IRA loves this). Also, we have to pay you guys transaction costs for this "hack"/patch? Sounds like a pretty good deal (NOT).

My suggestion: Remove this code and think of a better solution.

**Comment by rikterbeek** [comment]
Hi Franck,

Thanks for letting us know about your doubts about this. If a product is free and you don't have to pay for it the payment methods will not appear and you do not have to choose a payment method in magento. 

We are working on a subscription module where it is possible to discount a subscription product for 100% the first x of times. But because it is a subscription product we need payment details for the upcoming orders. That is why payment methods are shown and for Ideal,Sofort and SEPA extra costs is defined otherwise the payment cannot be done. We do not magically add extra costs, it will be shown to the customer that a extra fee is included into the order and he can view the total amount being set to 0.01 cent before doing the transaction. It will be in the invoice as well. We use magento total system for this.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Franck,

I see that we have forgotten about the check that the amount needs to be zero to only be supplied. Something we will fix. Keep in mind that this is a development version branch so bugs can be committed.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Franck,

We have found out that this fee is before total amount so we cannot use this for subscription fee if amount is zero. We have created a new fee in our subscription module that makes this possible.
So we have reverted our change see: 188939838c5932694a5f37a0eec9a51fb9da39aa

Regards,
Rik
Adyen
