### ISSUE TITLE
Additional error in logs  Undefined index: is_checkout   + Notice: unserialize(): Error at offset 0 of 8 bytes  in 

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#410]
Error 1 in log
2015-09-08T20:30:34+00:00 ERR (3): 08-09-2015 22:30:34 Notice: Undefined index: is_checkout  in /home/user/domains/domain.com/public_html/.modman/magento/app/code/community/Adyen/Payment/Helper/Data.php on line 40

Error 2 in log
2015-09-08T20:36:53+00:00 ERR (3): 08-09-2015 22:36:53 Notice: unserialize(): Error at offset 0 of 8 bytes  in /home/user/domains/domain.com/public_html/.modman/magento/app/code/community/Adyen/Payment/Block/Form/Abstract.php on line 75

**Comment by rikterbeek** [comment]
Hi Sean,

Both are notice so not a big issue. How are you logging these errors and what log file are they located ?

If I look into the code the first error should never occur because you can see here:
https://github.com/Adyen/magento/blob/develop-2.3.2/app/code/community/Adyen/Payment/Helper/Data.php#L36
that the cctypes are retrieved in the config all cctypes has the field is_checkout located see:
https://github.com/Adyen/magento/blob/develop-2.3.2/app/code/community/Adyen/Payment/etc/config.xml#L444-L517

The second error is fine, this is in a try catch block so this will go as expected. see:
https://github.com/Adyen/magento/blob/master/app/code/community/Adyen/Payment/Block/Form/Abstract.php#L74-L78

Regards,
Rik
Adyen

**Comment by simonrl** [comment]
The first error occured for me too when I updated the extension from v2.2.2 to v2.4.0.1 and loaded the payment method page in the backend for the first time

**Comment by rikterbeek** [comment]
Hi simonrl,

Really strange because you can see that it is there and I don't have this at all.

Regards,
Rik
Adyen

**Comment by newLoki** [comment]
Had almost the same issue as you mentioned as point 1.
Refreshing the config cache in magento (System -> Cache -> Configuration Cache) did the job for me.
