### ISSUE TITLE
All API Payments should call Mage_Sales_Model_Quote::reserveOrderId()

### ISSUE THREAD

**Issue by paales** [Adyen/magento#438]
![schermafbeelding 2015-10-14 om 14 29 50](https://cloud.githubusercontent.com/assets/1244416/10483805/8ca098c8-7281-11e5-9a3d-d5f3f82859ea.png)

- Adyen CC
- Adyen OneClick

**Comment by rikterbeek** [comment]
Hi Paul,

Could you verify if this fix solve the issue for the subscription module.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Paul,

Check my latest changes. Maybe with this fix the:
$quote = Mage::getModel('sales/quote')
            ->load($quoteId)
            ->setReservedOrderId($incrementId)
            ->save();
is not needed anymore.

I want to put the Adyen_Payment_Exception back to Mage::throwException because it can now not show the error message to the client. We need to check if this won't break the subscription module.

Regards,
Rik
Adyen
