### ISSUE TITLE
unserialize(): Error at offset 0 of 13 bytes

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/magento#445]
Just a notice, but we see it in logging

Notice: unserialize(): Error at offset 0 of 13 bytes  in /home/user/domains/domain.com/public_html/.modman/magento/app/code/community/Adyen/Payment/Block/Form/Abstract.php on line 75

**Comment by rikterbeek** [comment]
Hi Sean,

Something to ignore. Unserialize can go wrong if it is empty there is already a check if this failed to return empty array see code: https://github.com/Adyen/magento/blob/develop/app/code/community/Adyen/Payment/Block/Form/Abstract.php#L74-77 

Regards,
Rik

**Comment by frenck** [comment]
@rikterbeek I'm guessing you're missing @shirtsofholl point...

It's creating log entries on the server side... maybe you want to check this before calling unserialize() instead.

**Comment by rikterbeek** [comment]
Hi @frenck,

I think there comes a lot of overhead if you want to check if a string is serialized or not. see for example: https://gist.github.com/cs278/217091.  

What you can do is add an operator so the notice will be ignored. http://www.php.net/manual/en/language.operators.errorcontrol.php
See as well this post:
http://stackoverflow.com/questions/1369936/check-to-see-if-a-string-is-serialized

But @ operators is discouraged by PHP codeSniffer so that is why we do not do this.

Regards,
Rik
Adhen

**Comment by seansan** [comment]
Hi! What is causing the unserialized strign anyways? I see it in our logs several times a day. Maybe the function creating the serialized data can instead of sending an empty string send a certain serialized variable, that when read means: I am empty?

**Comment by shirtsofholl** [comment]
2016-03-01T15:43:21+00:00 ERR (3): Notice: unserialize(): Error at offset 0 of 8 bytes  in app/code/community/Adyen/Payment/Block/Form/Abstract.php on line 75

Still exists in 2.5.3
