### ISSUE TITLE
HPP iDEAL Show iDEAL bank logos does not show

### ISSUE THREAD

**Issue by michael85a** [Adyen/magento#446]
HPP iDEAL Show iDEAL bank logos does not show

app\code\community\Adyen\Payment\Model\Adyen\Ideal.php
have public function getIssuers()
it reads $this->getConfigData('issuers')

in system xml there is no issuers 

in frontend can not select the bank

http://i.imgur.com/lsEe4zS.png

how to be in this case?

**Comment by rikterbeek** [comment]
Hi michael85a,

This is loaded dynamically from the observer. The issue here is that the response of adyen did not receive issuers data. Could you check if you have enabled Adyen HPP payment method and you have correctly configured the merchant account, skincode and HMAC key. Keep in mind that in the release version of the module you need to use the old SHA1 signature skin.

Regards,
Rik
Adyen

**Comment by michael85a** [comment]
issue solved!
thanks a lot!!!!

**Comment by rikterbeek** [comment]
great!
