### ISSUE TITLE
Process all notification through a cronjob

### ISSUE THREAD

**Issue by rikterbeek** [Adyen/magento#458]

**Comment by questionmark78** [comment]
Is there already release date planned for release 2.5.0
We have more and more issues with this.

**Comment by rikterbeek** [comment]
Hi questionmark78,

What magento version are you running ? It is tested against 1.9.x versions so if you are running that use this beta version.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
I haven't checked the solution, but are all notifications now via cron?

I ask because we recently had a jamming cron job where other cron jobs would not run anymore. of course we tried to fix this asap - but it would be really great if core processes like payment processing does NOT stop because the cron doesnt run

**Comment by rikterbeek** [comment]
Hi shirtsofholland,

Yes all notifications are being processed through the cron. Receiving the notifications will ofcourse always work. So accepting payments will always going trough. Only the processing of the notifications will go over a cronjob. We have chosen a cronjob because only in this case we can be sure every notification is processed after each other and we don't have any multi threading issues we had before.

Regards,
Rik
Adyen
