### ISSUE TITLE
Order is set to pending after authorisation completes

### ISSUE THREAD

**Issue by gigadesign1** [Adyen/magento#470]
This happens rarely, but is a very big issue for us.

Sometimes after the plugin sets the order to processing, it adds another comment with the status pending, resulting that the order status is pending payment, but the state is processing.
This means the order is not automaticly shipped by us, until someone notices.

See an example here:
![pending](https://cloud.githubusercontent.com/assets/1337445/11438897/5c08bf62-94f8-11e5-9d80-de07d6f7b82b.jpg)

**Comment by rikterbeek** [comment]
Hi Mark,

We have solved this issue by letting a cronjob execute the notifications instead of directly when the notification is received. This version is now in beta see: https://github.com/Adyen/magento/tree/release-2.5.0.

Regards,
Rik
Adyen

**Comment by gigadesign1** [comment]
Thanks! I'll wait for the stable release.

Different question; we are investigating on moving to Magento 2.0. Will there be a Adyen plugin for that version? If so, when can we expect it?

**Comment by rikterbeek** [comment]
Hi Mark,

Yes, We are in the Magento Connect Launch Program from Magento. We already build a module for the merchant beta version. I have just changes this module to let it work with Magento 2.0.0 release version as well. We have it in a private repository because we are working on it, but we can provide you access if needed. It now has functionality to do creditcard payment inside Magento checkout with CSE and redirect to our HPP for alternative payment methods. We will expand the features quickly so it will have all the same functionalities this version has.

Regards,
Rik
Adyen

**Comment by gigadesign1** [comment]
Great! We are just in the fase of investigating the impact, so we didn't even start developing yet. Just checking which partners are going to offer a new extension.

Keep up the good work, and have a great weekend! :)
