### ISSUE TITLE
Error on retry order after cancelation

### ISSUE THREAD

**Issue by gigadesign1** [Adyen/magento#517]
Version 2.5.0

After the customer cancels a payment, the customer gets a database error message when trying to place the order again.
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '000088882' for key 'UNQ_SALES_FLAT_ORDER_INCREMENT_ID'

Steps to reproduce:
Place order with iDeal test issuer canceled.
Select iDeal test issuer to try again.
Error message is displayed.

**Comment by rikterbeek** [comment]
Hi Mark,

Could not reproduce this. I don't this issue is caused by our module. What kind of incrementation do you use for your orders. Is this the default or not ? If not this could help you out I think:
http://www.thevortexcode.com/solved-unq_sales_flat_order_increment_id-in-magento/

Regards,
Rik

**Comment by gigadesign1** [comment]
I uderstand the error message, It means the temporary order ID is not handled correctly in the quote.

We only experience this with Adyen payment methods, not with Paypal or our old PSP.

I will check if I can reproduce in the master branch tonight

**Comment by gigadesign1** [comment]
This was an issue from another module  extending the quote core class. This is fixed.
