### ISSUE TITLE
Possible performance problem Adyen_Payment_Model_Billing_Agreement_Observer::_addOneClickMethodsToConfig

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#546]
When profiling our site we see this takes quite long (and seems to first been seen since the last upgrade). Can someone confirm this?

Adyen_Payment_Model_Billing_Agreement_Observer::_addOneClickMethodsToConfig 2.9391

ps. and is there a possible workaround? (disable oneclick recurring maybe??)

**Comment by rikterbeek** [comment]
Hi Sean,

This is strange because you do not have recurring_contract notification enabled on your account. Do you have any billing agreements in your magento store? You can just disable the Adyen OneClick payment method.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
ah maybe this is where it goes wrong, so my options are

1. turn on recurring_contract? and then Adyen OneClick payment method
works. Is this correct?

2. Turn off Adyen OneClick payment

thanks, Sean

**Comment by rikterbeek** [comment]
Hi Sean,

Both are correct.

Regards,
Rik

**Comment by seansan** [comment]
We turned off oneclick. Also debugging with AOE profiler.  Now log is couple of MB with this:

Dont knoww exactly what it is. Rik?

2016-03-08T15:24:18+00:00 DEBUG (7): [INVALID NESTING!] Found: OBSERVER: adyen_payment_billing_agreement | Expecting: Adyen_Payment_Model_Billing_Agreement_Observer::_addOneClickMethodsToConfig
2016-03-08T15:24:18+00:00 DEBUG (7): Auto-stopping timer "Adyen_Payment_Model_Billing_Agreement_Observer::_addOneClickMethodsToConfig" because of incorrect nesting

**Comment by rikterbeek** [comment]
Hi Sean,

I have installed this profiler now but can't see this issue in my logs. It could be that it is caused by external modules as for example a checkout module.  If you have turn oneclick off this code should not be executed at all. I have looked into the invalided nesting issue and it can be safely ignored. You can just disable the logging of this in the settings of the AOE profiler configurations. 

I can see that the core of magento code they have this issue as well see for example:

2016-03-09T09:38:36+00:00 DEBUG (7): [INVALID NESTING!] Found: mage::dispatch::controller::action::checkout_onepage_progress | Expecting: layout/db_update: checkout_onepage_progress_billing

Regards,
Rik
Adyen

**Comment by seansan** [comment]
I suggest to close issue
