### ISSUE TITLE
Make selecting a bank mandatory when selecting iDeal

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#606]
Currently, when a customer selects iDeal but doesn't select a bank, he is sent to a random bank. Instead, the customer should be forced to select a bank before submitting the order.
Edit: This only occurs when "Show iDeal logo's" is set to yes.

**Comment by oblomovx** [comment]
Proposed solution:
add the class "validate-one-required-by-name" to the last radio-button in the iDeal form.

**Comment by rikterbeek** [comment]
@oblomovx,

There is server validation if this selection is made so strange that it is redirected to a random bank. see: https://github.com/Adyen/magento/blob/develop/app/code/community/Adyen/Payment/Model/Adyen/Hpp.php#L117-L124 . I will move this into the Ideal.php because it is only used there but this should work because Ideal extends from HPP

We can add front-end validation as well then it is better to us "validate-one-required" on the last element.
I will add this for you.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @oblomovx,

See additional front-end validation in the commit above.

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Nice, thank you!
