### ISSUE TITLE
Redirect after payment with app

### ISSUE THREAD

**Issue by oblomovx** [Adyen/magento#616]
When a customer places an order from his phone with the non standard browser (eg chrome on ios ) and the order is paid via the app from their bank (eg ING, Rabobank), the bank's app redirects back to the succes page using the standard browser (safari). As the cookies and sessions don't match, the customer gets an empty shopping cart instead of the success page, which is very confusing. 

I don't know who should fix this (Adyen, banks, Apple), or if it can be fixed at all, but it is causing quite a bit of confusion on the customers side.

**Comment by rikterbeek** [comment]
Hi @oblomovx,

I understand your issue but this issue is on apple because it is always pushing you back to safari instead of android where you have the option to what browser you want to return. We are triggering the success page of Magento because session does not matter but magento core is checking on that url if the session is valid something magento should not do. You could do a rewrite on the core of magento to solve this issue.

Regards,
Rik
Adyen
