### ISSUE TITLE
exception 'Mage_Core_Exception' with message 'Mismatch between Live/Test modes of Magento store and the Adyen platform'

### ISSUE THREAD

**Issue by elfeffe** [Adyen/magento#638]
I have logs like this
`exception 'Mage_Core_Exception' with message 'Mismatch between Live/Test modes of Magento store and the Adyen platform'`

It happens some days, **we never change Live/Test settings**

Somebody else with the same problem?

**Comment by rikterbeek** [comment]
Hi @elfeffe,

This means you have setup a endpoint on Adyen Test or Live to your Magento store that is not in the same mode. This can be two things:

* Your Magento is on production modus but you have setup a endpoint on Adyen Test to link to this Magento instance

* Your Magento is on test modus but you have setup a endpoint on Adyen Live to link to this Magento instance.

We block this notification because this should never happen!

Regards,
Rik
Adyen
